"""creditos_video

Revision ID: 2affdd438092
Revises: f9fdc4554ff6
Create Date: 2025-03-31 23:05:13.783268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2affdd438092'
down_revision: Union[str, None] = 'f9fdc4554ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_video_credit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tb_video_credit_id'), 'tb_video_credit', ['id'], unique=False)
    op.create_table('tb_video_credit_transaction',
    sa.Column('video_credit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'consumption', 'refund', name='transaction_types'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_credit_id'], ['tb_video_credit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_tb_video_credit_transaction_id'), 'tb_video_credit_transaction', ['id'], unique=False)
    op.alter_column('tb_video', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_video', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_tb_video_credit_transaction_id'), table_name='tb_video_credit_transaction')
    op.drop_table('tb_video_credit_transaction')
    op.drop_index(op.f('ix_tb_video_credit_id'), table_name='tb_video_credit')
    op.drop_table('tb_video_credit')
    # ### end Alembic commands ###
