"""add_video_duration_fields

Revision ID: add_video_duration_fields
Revises: ae0b4eb4fc71
Create Date: 2025-04-01 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_video_duration_fields'
down_revision: Union[str, None] = 'ae0b4eb4fc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_video', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('tb_video', sa.Column('generation_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_video', 'generation_time')
    op.drop_column('tb_video', 'duration')
    # ### end Alembic commands ###