"""add_video_fields

Revision ID: c9ad29d42cac
Revises: add_video_duration_fields
Create Date: 2025-04-03 10:28:42.209980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ad29d42cac'
down_revision: Union[str, None] = 'add_video_duration_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_video', sa.Column('solicitacao', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('roteiro', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('frases', sa.JSON(), nullable=True))
    op.add_column('tb_video', sa.Column('hashtags', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('conteudo', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('imagens', sa.JSON(), nullable=True))
    op.add_column('tb_video', sa.Column('narracao_marcada', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('arquivo_narracao_raw', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('arquivo_narracao_remix', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('arquivo_video', sa.String(), nullable=True))
    op.add_column('tb_video', sa.Column('data_registro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_video', 'data_registro')
    op.drop_column('tb_video', 'arquivo_video')
    op.drop_column('tb_video', 'arquivo_narracao_remix')
    op.drop_column('tb_video', 'arquivo_narracao_raw')
    op.drop_column('tb_video', 'narracao_marcada')
    op.drop_column('tb_video', 'imagens')
    op.drop_column('tb_video', 'conteudo')
    op.drop_column('tb_video', 'hashtags')
    op.drop_column('tb_video', 'frases')
    op.drop_column('tb_video', 'roteiro')
    op.drop_column('tb_video', 'solicitacao')
    # ### end Alembic commands ###
